### ISSUE TITLE
SproutCore 1.5 support?

### ISSUE THREAD

**Issue by erichocean** [FrozenCanuck/Lebowski#14]
I'll admit I haven't tried it, but the README indicated it was 1.4.x only. Any ETA or info on what needs to be done?

**Comment by FrozenCanuck** [comment]
I'll be working on Lebowski to work with both Selenium 2 and SproutCore 1.5. However I don't have an ETA right now.

**Comment by robmonie** [comment]
For what it's worth, we're really interested in using Lebowski on a new SC 1.5 project as well.

**Comment by FrozenCanuck** [comment]
I'm with ya :). 

I actually have Lebowski working with the latest version of SproutCore 1.x (not SC 2.0) and its working perfectly -- not to mention that I've updated it to run very fast! The updates however are internal and need to go through a legal post-back review, but I'm hoping to push it through sometime mid to late July. I realize the public version of Lebowski has been dormant for the last few months, but I hope to change that sometime this summer and get public commits out there on a frequent enough basis.  

My apologies to you and everyone else who want to use the latest Lebowski but haven't heard much.

**Comment by robmonie** [comment]
That's brilliant news. Thanks for replying so quickly!!

**Comment by FrozenCanuck** [comment]
Lebowski has been updated to support 1.5 and 1.6. https://rubygems.org/gems/lebowski
