### ISSUE TITLE
SC 1.6 support

### ISSUE THREAD

**Issue by rvalle** [FrozenCanuck/Lebowski#17]
Is there support for the latest SC 1.6 version?

We have migrated our service from 1.5, and are about to migrate the Lebowski tests.

Some controls seem to work, others seem to be broken.

Is SC 1.6 supported?

**Comment by FrozenCanuck** [comment]
Yep, I'm planning on getting out the latest Lebowski code to the public ASAP. Lebowski will support SC 1.6. One note: The code has to go through an internal post-back review, which can take a couple of days. I'm hoping to having everything released sometime in the next week or two.

**Comment by rvalle** [comment]
Thanks!! Really look fordward to it! :)

**Comment by scytacki** [comment]
Has there been any progress on this?  We are migrating to 1.6 and would like to get our tests working again.  We might go ahead and try to fix the issues ourselves, so any status update or pointers would be very useful.

**Comment by FrozenCanuck** [comment]
Internal updates for Lebowski are now being put into the post-back review. This will take a few of days since legal has to go through everything. Once the review is complete and all is good, then I can push all the changes out to the public. Lebowski will support both SC 1.5 and SC 1.6.

**Comment by rvalle** [comment]
great!!

**Comment by joegaudet** [comment]
Can't wait!

**Comment by CRIZN** [comment]
pumped

**Comment by FrozenCanuck** [comment]
Lebowski has been updated to support 1.5 and 1.6. Enjoy! :)

https://rubygems.org/gems/lebowski

**Comment by rvalle** [comment]
Yeahhhhh!!, great news!

Thanks!!

**Comment by CRIZN** [comment]
You sir are a gentleman and a scholar.
