### ISSUE TITLE
segmentItem.selected? fail

### ISSUE THREAD

**Issue by Fodoj** [FrozenCanuck/Lebowski#19]
This is true:

```
  @mainTabs.segmentedView.childViews[1].isSelected.should be_true
```

This is false:

```
  @mainTabs.segmentedView.buttons[1].selected?.should be_true
```

Am i using assertion wrong or there is some lebowski bug? :)

**Comment by FrozenCanuck** [comment]
Hmm, interesting. I've run tests on my end but both assertions are passing. Just for kicks, could you try the following statements as well:

```
@mainTabs.segmentedView.buttons[1].should be_selected

@mainTabs.segmentedView.child_views[1].should be_selected

@mainTabs.segmentedView.buttons.should have_selected 1
```

In addition, what version of SproutCore are you running?

**Comment by Fodoj** [comment]
I am using SC 1.7.1beta (edge, i guess). 

This 3 examples passed fine. Don't know what's wrong with first one. I will use "should have_selected 1" =)

btw, can you check my last google group message, please? this facebook login and openedWindows thing confuses me.

p.s. awesome example apps! really helpfull

**Comment by FrozenCanuck** [comment]
Glad to know the three statements all passed. I tried running the statement that failed for you but it's still passing even with the latest SC. And, yep, I'll get back to you on the Facebook login shortly :)
