### ISSUE TITLE
Lebowski does not work with rspec 2.6.0

### ISSUE THREAD

**Issue by adamjmurray** [FrozenCanuck/Lebowski#22]
I am trying to use Lebowski in a project that requires rspec 2.6.0+. Bundler cannot install Lebowski in my project due to the requirement that Lebowski rspec (~> 2.5.0). I can hack my way around that, but I would love to use Lebowski's rspec integration.

Any plans to get this updated to work with rspec 2.6 any time soon?

**Comment by FrozenCanuck** [comment]
Yep, I'll update Lebowski to work with rspec 2.6 and up. Thanks for the notice :)
